--[[
	EnemyData - every enemy, mini-boss and boss.

	Stats are the values at minute 0; WaveManager scales HP / damage with run time.
	  HP, Speed (studs/s), Damage (contact, per hit), XP (gem value), Radius (collision, studs)
	  Model     - client model style (Render/EnemyModels.lua)
	  Scale     - visual size multiplier of that model
	  Behavior  - server AI (Sim/EnemyManager.lua)
	  Mass      - knockback resistance (knockback / Mass)
	  Params    - behaviour specific numbers

	The list order is the network id (uint8) - append new enemies at the end.
]]

export type EnemyDef = {
	Id: number,
	Key: string,
	Name: string,
	Desc: string,
	HP: number,
	Speed: number,
	Damage: number,
	XP: number,
	Radius: number,
	Scale: number,
	Model: string,
	Color: Color3,
	Accent: Color3,
	Behavior: string,
	Mass: number,
	CoinChance: number,
	ItemChance: number,
	Boss: boolean?,
	MiniBoss: boolean?,
	Rare: boolean?,
	Secret: boolean?,
	NoContact: boolean?,
	Collection: boolean?,
	Params: { [string]: any },
}

local rgb = Color3.fromRGB

local LIST: { EnemyDef } = ({
	{
		Key = "Goober",
		Name = "Goober",
		Desc = "A wobbly little guy. Weak alone, annoying in groups.",
		HP = 8,
		Speed = 10,
		Damage = 5,
		XP = 1,
		Radius = 1.3,
		Scale = 1,
		Model = "Blob",
		Color = rgb(120, 220, 90),
		Accent = rgb(70, 160, 50),
		Behavior = "Chase",
		Mass = 1,
		CoinChance = 0.008,
		ItemChance = 1,
		Collection = true,
		Params = {},
	},
	{
		Key = "NPC",
		Name = "NPC",
		Desc = "Walks slowly. Stares. Has no thoughts. Head empty.",
		HP = 20,
		Speed = 7.5,
		Damage = 7,
		XP = 2,
		Radius = 1.4,
		Scale = 1,
		Model = "Npc",
		Color = rgb(163, 162, 165),
		Accent = rgb(13, 105, 172),
		Behavior = "Chase",
		Mass = 1.5,
		CoinChance = 0.012,
		ItemChance = 1,
		Collection = true,
		Params = {},
	},
	{
		Key = "FastGuy",
		Name = "Fast Guy",
		Desc = "Always late for something. Runs straight at you.",
		HP = 6,
		Speed = 18.5,
		Damage = 5,
		XP = 1,
		Radius = 1.1,
		Scale = 1,
		Model = "Skinny",
		Color = rgb(255, 80, 70),
		Accent = rgb(255, 210, 60),
		Behavior = "Chase",
		Mass = 0.7,
		CoinChance = 0.008,
		ItemChance = 1,
		Collection = true,
		Params = {},
	},
	{
		Key = "TankNPC",
		Name = "Tank NPC",
		Desc = "An NPC that went to the gym once. Hits hard, shrugs off knockback.",
		HP = 140,
		Speed = 6.5,
		Damage = 14,
		XP = 8,
		Radius = 2.6,
		Scale = 1,
		Model = "Brute",
		Color = rgb(110, 115, 135),
		Accent = rgb(60, 60, 75),
		Behavior = "Chase",
		Mass = 6,
		CoinChance = 0.06,
		ItemChance = 3,
		Collection = true,
		Params = {},
	},
	{
		Key = "ScreamingGuy",
		Name = "Screaming Guy",
		Desc = "AAAAAAAAA. Stops, screams, then charges.",
		HP = 13,
		Speed = 11,
		Damage = 9,
		XP = 3,
		Radius = 1.3,
		Scale = 1,
		Model = "Screamer",
		Color = rgb(255, 214, 80),
		Accent = rgb(200, 40, 40),
		Behavior = "Charge",
		Mass = 1,
		CoinChance = 0.015,
		ItemChance = 1,
		Collection = true,
		Params = { Trigger = 24, Windup = 0.5, DashSpeed = 36, DashTime = 0.85, Rest = 1.1 },
	},
	{
		Key = "Goblin67",
		Name = "67 Goblin",
		Desc = "Rare. Runs away with a bag of coins. Catch it!",
		HP = 67,
		Speed = 15,
		Damage = 0,
		XP = 20,
		Radius = 1.4,
		Scale = 1,
		Model = "Goblin",
		Color = rgb(255, 200, 40),
		Accent = rgb(120, 70, 20),
		Behavior = "Flee",
		Mass = 1.5,
		CoinChance = 1,
		ItemChance = 0,
		Rare = true,
		NoContact = true,
		Collection = true,
		Params = { Lifetime = 20, Coins = 30, Chest = true },
	},
	{
		Key = "SigmaNPC",
		Name = "Sigma NPC",
		Desc = "Keeps its distance. Fires mog beams. Never blinks.",
		HP = 34,
		Speed = 11.5,
		Damage = 8,
		XP = 6,
		Radius = 1.4,
		Scale = 1,
		Model = "Suit",
		Color = rgb(30, 30, 38),
		Accent = rgb(255, 205, 60),
		Behavior = "Strafe",
		Mass = 2,
		CoinChance = 0.03,
		ItemChance = 2,
		Collection = true,
		Params = { Orbit = 22, ShootEvery = 3.4, ProjSpeed = 21, ProjDamage = 9, ProjRadius = 1.3, ProjLife = 3.5 },
	},
	{
		Key = "GlitchedNPC",
		Name = "Glitched NPC",
		Desc = "Missing texture energy. Teleports closer when you look away.",
		HP = 26,
		Speed = 8,
		Damage = 9,
		XP = 4,
		Radius = 1.4,
		Scale = 1,
		Model = "Glitch",
		Color = rgb(255, 0, 220),
		Accent = rgb(20, 20, 20),
		Behavior = "Blink",
		Mass = 1.5,
		CoinChance = 0.02,
		ItemChance = 1,
		Collection = true,
		Params = { Every = 2.6, Distance = 11, MinRange = 9 },
	},
	{
		Key = "DoubleGoober",
		Name = "Double Goober",
		Desc = "Two goobers in a trench coat. Splits when popped.",
		HP = 36,
		Speed = 8.5,
		Damage = 8,
		XP = 3,
		Radius = 2.1,
		Scale = 1.7,
		Model = "Blob",
		Color = rgb(80, 200, 170),
		Accent = rgb(40, 130, 110),
		Behavior = "Chase",
		Mass = 2.5,
		CoinChance = 0.02,
		ItemChance = 1,
		Collection = true,
		Params = { SplitInto = "Goober", SplitCount = 2 },
	},
	{
		Key = "GiantBrainrot",
		Name = "Giant Brainrot",
		Desc = "Mini-boss. A brain so rotten it grew legs. Slams the ground and spawns goobers.",
		HP = 5000,
		Speed = 8,
		Damage = 20,
		XP = 120,
		Radius = 5,
		Scale = 1,
		Model = "Brain",
		Color = rgb(255, 150, 190),
		Accent = rgb(200, 80, 130),
		Behavior = "Boss",
		Mass = 40,
		CoinChance = 1,
		ItemChance = 0,
		MiniBoss = true,
		Collection = true,
		Params = {
			Title = "GIANT BRAINROT",
			Patterns = { "Slam", "Summon" },
			SlamEvery = 5.5,
			SlamRadius = 12,
			SlamDelay = 1.1,
			SlamDamage = 24,
			SummonEvery = 9,
			SummonKey = "Goober",
			SummonCount = 6,
			Coins = 60,
		},
	},
	{
		Key = "SigmaOverlord",
		Name = "Sigma Overlord",
		Desc = "Boss. The final form of the grindset. Dashes, mogs, summons followers.",
		HP = 34000,
		Speed = 10,
		Damage = 28,
		XP = 400,
		Radius = 4.6,
		Scale = 1,
		Model = "Overlord",
		Color = rgb(25, 25, 32),
		Accent = rgb(255, 205, 60),
		Behavior = "Boss",
		Mass = 60,
		CoinChance = 1,
		ItemChance = 0,
		Boss = true,
		Collection = true,
		Params = {
			Title = "SIGMA OVERLORD",
			Patterns = { "Dash", "Ring", "Summon" },
			DashEvery = 6,
			DashWindup = 1.0,
			DashSpeed = 58,
			DashLength = 55,
			DashDamage = 30,
			RingEvery = 7,
			RingCount = 16,
			RingSpeed = 20,
			RingDamage = 14,
			SummonEvery = 12,
			SummonKey = "SigmaNPC",
			SummonCount = 4,
			Coins = 150,
		},
	},
	{
		Key = "King67",
		Name = "The 67 King",
		Desc = "Boss. Six. Seven. Six. Seven. Slams twice and spins 67 energy.",
		HP = 34000,
		Speed = 9.5,
		Damage = 26,
		XP = 400,
		Radius = 4.8,
		Scale = 1,
		Model = "King",
		Color = rgb(255, 200, 40),
		Accent = rgb(170, 60, 255),
		Behavior = "Boss",
		Mass = 60,
		CoinChance = 1,
		ItemChance = 0,
		Boss = true,
		Collection = true,
		Params = {
			Title = "THE 67 KING",
			Patterns = { "DoubleSlam", "Spiral", "Summon" },
			SlamEvery = 6.7,
			SlamRadius = 11,
			SlamDelay = 1.0,
			SlamDamage = 26,
			SpiralEvery = 8,
			SpiralCount = 20,
			SpiralSpeed = 19,
			SpiralDamage = 13,
			SummonEvery = 13,
			SummonKey = "Goblin67",
			SummonCount = 1,
			Coins = 150,
		},
	},
	{
		Key = "FinalGoober",
		Name = "THE FINAL GOOBER",
		Desc = "Final boss. The first goober. The last goober. Survive it to win the run.",
		HP = 150000,
		Speed = 10,
		Damage = 34,
		XP = 1000,
		Radius = 7,
		Scale = 4.2,
		Model = "Blob",
		Color = rgb(150, 255, 90),
		Accent = rgb(255, 60, 160),
		Behavior = "Boss",
		Mass = 120,
		CoinChance = 1,
		ItemChance = 0,
		Boss = true,
		Collection = true,
		Params = {
			Title = "THE FINAL GOOBER",
			Final = true,
			Patterns = { "Slam", "Ring", "Rain", "Spiral" },
			SlamEvery = 5,
			SlamRadius = 14,
			SlamDelay = 1.0,
			SlamDamage = 30,
			RingEvery = 6.5,
			RingCount = 20,
			RingSpeed = 21,
			RingDamage = 15,
			RainEvery = 11,
			RainCount = 14,
			SpiralEvery = 9,
			SpiralCount = 24,
			SpiralSpeed = 20,
			SpiralDamage = 14,
			EnrageAt = 0.5,
			Coins = 400,
		},
	},
	{
		Key = "GoldenGoober",
		Name = "Golden Goober",
		Desc = "Secret. 1 in 500 goobers is made of pure gold.",
		HP = 40,
		Speed = 9,
		Damage = 5,
		XP = 25,
		Radius = 1.3,
		Scale = 1.15,
		Model = "Blob",
		Color = rgb(255, 205, 50),
		Accent = rgb(255, 245, 170),
		Behavior = "Chase",
		Mass = 1,
		CoinChance = 1,
		ItemChance = 0,
		Rare = true,
		Secret = true,
		Collection = true,
		Params = { Coins = 67 },
	},
	{
		Key = "TheNPC",
		Name = "The NPC",
		Desc = "Secret. It was just standing there. Menacingly.",
		HP = 300,
		Speed = 2.5,
		Damage = 0,
		XP = 67,
		Radius = 1.5,
		Scale = 1.25,
		Model = "Npc",
		Color = rgb(245, 205, 48),
		Accent = rgb(40, 127, 71),
		Behavior = "Stand",
		Mass = 99,
		CoinChance = 1,
		ItemChance = 0,
		Rare = true,
		Secret = true,
		NoContact = true,
		Collection = true,
		Params = { Coins = 100, Chest = true, Lifetime = 60 },
	},
	{
		Key = "Runner",
		Name = "Why Is He Running",
		Desc = "Event. Nobody knows why he is running. Catch him for a chest.",
		HP = 90,
		Speed = 26,
		Damage = 0,
		XP = 30,
		Radius = 1.3,
		Scale = 1.2,
		Model = "Skinny",
		Color = rgb(255, 215, 60),
		Accent = rgb(255, 255, 255),
		Behavior = "Orbit",
		Mass = 99,
		CoinChance = 1,
		ItemChance = 0,
		Rare = true,
		NoContact = true,
		Collection = true,
		Params = { Radius = 20, Lifetime = 16, Coins = 30, Chest = true },
	},
	{
		Key = "Crate",
		Name = "Sus Box",
		Desc = "Loot crate. Break it for pizza, magnets and bombs.",
		HP = 1,
		Speed = 0,
		Damage = 0,
		XP = 0,
		Radius = 1.6,
		Scale = 1,
		Model = "Crate",
		Color = rgb(170, 110, 60),
		Accent = rgb(255, 230, 90),
		Behavior = "Static",
		Mass = 999,
		CoinChance = 0,
		ItemChance = 0,
		NoContact = true,
		Params = { Lifetime = 60 },
	},
} :: any)

local EnemyData = {}
EnemyData.List = LIST
EnemyData.ByKey = {} :: { [string]: EnemyDef }
EnemyData.ById = {} :: { [number]: EnemyDef }

for id, def in LIST do
	def.Id = id
	EnemyData.ByKey[def.Key] = def
	EnemyData.ById[id] = def
end

-- Bosses that can appear at the 10 minute mark (one is picked per run)
EnemyData.MidBosses = { "SigmaOverlord", "King67" }

function EnemyData.Get(key: string): EnemyDef
	local def = EnemyData.ByKey[key]
	assert(def, "unknown enemy " .. tostring(key))
	return def
end

return EnemyData
