return {
	{
		name = "Heavy Lifting",
		chapter = "Crates and Lifts",
		hint = "Push the crate out of the tunnel.",
		map = {
			"                                                      ",
			"                                                      ",
			"                                                      ",
			"                                                      ",
			"                                                      ",
			"                                                      ",
			"          ############                                ",
			"          ############                                ",
			"              11                                      ",
			"  S           11                  K             D     ",
			"#########################  #############  ############",
			"#########################^^#############  ############",
			"########################################  ############",
		},
	},
	{
		name = "Lift Off",
		chapter = "Crates and Lifts",
		hint = "Everyone on the lift, then over the spikes.",
		lift = { need = 99, rise = 4 },
		map = {
			"                                                  ",
			"                                                  ",
			"                                                  ",
			"                                                  ",
			"                                                  ",
			"                ######                            ",
			"                ######                            ",
			"                ######                            ",
			"                ######                            ",
			"  S        LLLLL######      K      ^^       D     ",
			"##################################################",
			"##################################################",
			"##################################################",
		},
	},
	{
		name = "Step by Step",
		chapter = "Crates and Lifts",
		hint = "A crate to climb, stairs, then a crate to push.",
		map = {
			"                                                                     ",
			"                                                                     ",
			"                                                                     ",
			"                                                                     ",
			"                                                                     ",
			"                                                                     ",
			"                                 ##########                          ",
			"                   ###    ###    ##########                          ",
			"                   ###   #####       11                              ",
			"  S          1     ###  #######      11                K       D     ",
			"##############################################  #####################",
			"##############################################^^#####################",
			"#####################################################################",
		},
	},
	{
		name = "Crate and Lift",
		chapter = "Crates and Lifts",
		hint = "Crate, lift and a plate - you know them all now.",
		lift = { need = 99, rise = 4 },
		button = { need = 4, latch = true },
		map = {
			"                                                                x             ",
			"                                                                x             ",
			"                                                                x             ",
			"                                                                x             ",
			"                                                 K              x             ",
			"                                    ######     ####             x             ",
			"          ############              ######                      x             ",
			"          ############              ######                      x             ",
			"              11                    ######                      x             ",
			"  S           11               LLLLL######   j            b     x       D     ",
			"#########################  ###################################################",
			"#########################^^###################################################",
			"##############################################################################",
		},
	},
	{
		name = "Crumbly Path",
		chapter = "Seesaws and Sand",
		hint = "Sand crumbles under your feet - keep moving!",
		map = {
			"                                               ",
			"                                               ",
			"                                               ",
			"                                               ",
			"                                               ",
			"                                               ",
			"                                               ",
			"                                               ",
			"                                               ",
			"  S                     K                D     ",
			"#############oooo##############ooo#############",
			"#############    ##############   #############",
			"#############    ##############   #############",
		},
	},
	{
		name = "Sandy Steps",
		chapter = "Seesaws and Sand",
		hint = "Sand, stairs and more sand. Don't stop!",
		map = {
			"                                                              ",
			"                                                              ",
			"                                                              ",
			"                                                              ",
			"                                  K                           ",
			"                                ####                          ",
			"                                                              ",
			"                                                              ",
			"                       ###                                    ",
			"  S                   #####   j                         D     ",
			"#############oooo###########################ooooo#############",
			"#############    ###########################     #############",
			"#############    ###########################     #############",
		},
	},
	{
		name = "Hourglass",
		chapter = "Seesaws and Sand",
		hint = "Sand and a clock: 90 seconds.",
		time = 90,
		map = {
			"                                                          ",
			"                                                          ",
			"                                                          ",
			"                                                          ",
			"                                                          ",
			"                                                          ",
			"                                                          ",
			"                                                          ",
			"                                                          ",
			"  S                               K                 D     ",
			"#############ooooo##### o o #############oooo#############",
			"#############     #####     #############    #############",
			"#############     #####     #############    #############",
		},
	},
	{
		name = "Sand Stones",
		chapter = "Seesaws and Sand",
		hint = "Hop across the crumbling stones.",
		time = 80,
		map = {
			"                                                             ",
			"                                                             ",
			"                                                             ",
			"                                                             ",
			"                                   K                         ",
			"                                 ####                        ",
			"                                                             ",
			"                                                             ",
			"                                                             ",
			"  S                            j                       D     ",
			"############ o o #####ooooo################# o o ############",
			"############     #####     #################     ############",
			"############     #####     #################     ############",
		},
	},
	{
		name = "Moving Floors",
		chapter = "Platforms and Two Colours",
		hint = "Hop on the moving platforms when they are low.",
		mover = { rise = 3, period = 4 },
		map = {
			"                                                ",
			"                                                ",
			"                                                ",
			"                                                ",
			"                                                ",
			"                                                ",
			"                                                ",
			"                                                ",
			"                                                ",
			"  S                     K                 D     ",
			"############  MM  ############  MM  ############",
			"############      ############      ############",
			"############      ############      ############",
		},
	},
	{
		name = "Platform Hop",
		chapter = "Platforms and Two Colours",
		hint = "Ride the platforms and open the purple wall.",
		button = { need = 4, latch = true },
		mover = { rise = 3, period = 4 },
		map = {
			"                                        x             ",
			"                                        x             ",
			"                                        x             ",
			"                                        x             ",
			"                                        x             ",
			"                                        x             ",
			"                                        x             ",
			"                                        x             ",
			"                                        x             ",
			"  S                         K     b     x       D     ",
			"############  MM  MM  ################################",
			"############          ################################",
			"############          ################################",
		},
	},
	{
		name = "High Ride",
		chapter = "Platforms and Two Colours",
		hint = "The key floats above a moving platform.",
		mover = { rise = 3, period = 3.8 },
		map = {
			"                                                                ",
			"                                                                ",
			"                                                                ",
			"                                                                ",
			"                                                                ",
			"                                      K                         ",
			"                                                                ",
			"                                                                ",
			"                                                                ",
			"  S                                           j^^^        D     ",
			"############  MM  MM  ####  MM  ####  MM  ######################",
			"############          ####      ####      ######################",
			"############          ####      ####      ######################",
		},
	},
	{
		name = "Two Colours",
		chapter = "Platforms and Two Colours",
		hint = "Purple and pink plates in one level.",
		button = { need = 4, latch = true },
		button2 = { need = 1, latch = true },
		mover = { rise = 3, period = 3.8 },
		map = {
			"                  x                                 y             ",
			"                  x                                 y             ",
			"                  x                                 y             ",
			"                  x                                 y             ",
			"                  x                  K              y             ",
			"                  x                ####             y             ",
			"                  x                                 y             ",
			"                  x                                 y             ",
			"                  x                                 y             ",
			"  S         b     x              j            c     y       D     ",
			"########################  MM  ####################################",
			"########################      ####################################",
			"########################      ####################################",
		},
	},
	{
		name = "Cannonballs",
		chapter = "Cannons and the Chase",
		hint = "Jump over the cannonballs and hide behind blocks.",
		cannon = { interval = 2.8, speed = 12 },
		map = {
			"                                            ",
			"                                            ",
			"                                            ",
			"                                            ",
			"                                            ",
			"                                            ",
			"                                            ",
			"                                            ",
			"                                            ",
			"  S           K      #    #      <    D     ",
			"############################################",
			"############################################",
			"############################################",
		},
	},
	{
		name = "High and Low",
		chapter = "Cannons and the Chase",
		hint = "Cannonballs fly low and high. Time your jumps!",
		cannon = { interval = 2.6, speed = 13 },
		map = {
			"                                                        ",
			"                                                        ",
			"                                                        ",
			"                                                        ",
			"                                                        ",
			"                                                        ",
			"                                                        ",
			"          >                                             ",
			"                                                        ",
			"  S                       K      #    #      <    D     ",
			"########################################################",
			"########################################################",
			"########################################################",
		},
	},
	{
		name = "The Chase",
		chapter = "Cannons and the Chase",
		hint = "The screen scrolls by itself - keep up with the red wall!",
		scroll = { speed = 3.2, delay = 4 },
		map = {
			"                                                                  ",
			"                                                                  ",
			"                                                                  ",
			"                                                                  ",
			"                                                                  ",
			"                                                                  ",
			"                                                                  ",
			"                                                                  ",
			"                                                                  ",
			"  S                ^^      ##       K     j^^^              D     ",
			"############  ######################################  ############",
			"############  ######################################  ############",
			"############  ######################################  ############",
		},
	},
	{
		name = "Cannon Sands",
		chapter = "Cannons and the Chase",
		hint = "Sand under cannon fire.",
		cannon = { interval = 2.6, speed = 13 },
		map = {
			"                                                                   ",
			"                                                                   ",
			"                                                                   ",
			"                                                                   ",
			"                                                                   ",
			"                                                                   ",
			"                                                                   ",
			"                                                                   ",
			"                                                                   ",
			"  S          #         <               K      #         <    D     ",
			"###########################ooooo###################################",
			"###########################     ###################################",
			"###########################     ###################################",
		},
	},
}
