--[[
	HeroData - the 15 playable heroes.

	Every hero has its own minimalist 3D model (shared/HeroModels.lua), a starting ability,
	stat bonuses (Stats keys, see shared/Stats.lua), a passive (the stats, in words) and ONE
	unique mechanic implemented in the run simulation (search Sim/ for the Mechanic key).

	Unlock: Default = true, or Fragments (earned in runs), and/or an Achievement.
	Secret heroes show "???" until they are unlocked.
]]

export type HeroDef = {
	Key: string,
	Name: string,
	Rarity: string,
	Desc: string,
	Passive: string,
	Mechanic: string,
	MechanicText: string,
	StartWeapon: string,
	Stats: { [string]: number },
	Color: Color3,
	Accent: Color3,
	Unlock: { Default: boolean?, Fragments: number?, Achievement: string? },
	Secret: boolean?,
}

local rgb = Color3.fromRGB

local LIST: { HeroDef } = ({
	{
		Key = "Rookie",
		Name = "THE ROOKIE",
		Rarity = "Common",
		Desc = "First day on the job. Learns fast.",
		Passive = "+10% XP, +1 reroll",
		Mechanic = "QuickStudy",
		MechanicText = "Quick Study: the first 5 level ups heal 15 HP.",
		StartWeapon = "BasicBlaster",
		Stats = { Growth = 0.1, Rerolls = 1 },
		Color = rgb(70, 130, 255),
		Accent = rgb(255, 150, 50),
		Unlock = { Default = true },
	},
	{
		Key = "Runner",
		Name = "THE RUNNER",
		Rarity = "Common",
		Desc = "Never stops moving. Never.",
		Passive = "+25% movement speed, -15% max HP",
		Mechanic = "Slipstream",
		MechanicText = "Slipstream: 20% chance to dodge a hit while moving.",
		StartWeapon = "Boomerang",
		Stats = { MoveSpeed = 0.25, MaxHPMult = -0.15 },
		Color = rgb(235, 60, 70),
		Accent = rgb(255, 255, 255),
		Unlock = { Default = true },
	},
	{
		Key = "Tank",
		Name = "THE TANK",
		Rarity = "Common",
		Desc = "Big. Heavy. Hard to knock over.",
		Passive = "+40% max HP, +1 armor, -15% movement speed",
		Mechanic = "Thorns",
		MechanicText = "Thorns: enemies that touch you take damage.",
		StartWeapon = "Shockwave",
		Stats = { MaxHPMult = 0.4, Armor = 1, MoveSpeed = -0.15 },
		Color = rgb(90, 150, 90),
		Accent = rgb(200, 205, 215),
		Unlock = { Default = true },
	},
	{
		Key = "Hunter",
		Name = "THE HUNTER",
		Rarity = "Uncommon",
		Desc = "Sees them coming from far away.",
		Passive = "+25% range, +10% crit chance",
		Mechanic = "Headhunter",
		MechanicText = "Headhunter: +40% damage to bosses and elites.",
		StartWeapon = "Arrow",
		Stats = { Range = 0.25, Crit = 0.1 },
		Color = rgb(60, 120, 70),
		Accent = rgb(170, 120, 70),
		Unlock = { Fragments = 15 },
	},
	{
		Key = "Collector",
		Name = "THE COLLECTOR",
		Rarity = "Uncommon",
		Desc = "Carries everything. Drops nothing.",
		Passive = "+60% pickup range, +25% coins",
		Mechanic = "Hoarder",
		MechanicText = "Hoarder: XP crystals are worth 15% more, coins drop 50% more often.",
		StartWeapon = "SigmaAura",
		Stats = { Magnet = 0.6, Greed = 0.25 },
		Color = rgb(40, 170, 170),
		Accent = rgb(255, 205, 60),
		Unlock = { Fragments = 15 },
	},
	{
		Key = "Samurai",
		Name = "THE SAMURAI",
		Rarity = "Rare",
		Desc = "One blade. Very sharp. Very fast.",
		Passive = "+15% area, +10% damage, +5% speed",
		Mechanic = "Iaijutsu",
		MechanicText = "Iaijutsu: every 4th katana slash deals x3 damage in a wider arc.",
		StartWeapon = "Katana",
		Stats = { Area = 0.15, Might = 0.1, MoveSpeed = 0.05 },
		Color = rgb(200, 40, 50),
		Accent = rgb(30, 30, 36),
		Unlock = { Fragments = 40 },
	},
	{
		Key = "Mage",
		Name = "THE MAGE",
		Rarity = "Rare",
		Desc = "Reads spell books for fun.",
		Passive = "-10% cooldowns",
		Mechanic = "ArcaneEcho",
		MechanicText = "Arcane Echo: missiles and bolts fire 1 extra projectile.",
		StartWeapon = "MagicMissile",
		Stats = { Cooldown = 0.1 },
		Color = rgb(120, 70, 220),
		Accent = rgb(90, 230, 255),
		Unlock = { Fragments = 40 },
	},
	{
		Key = "Engineer",
		Name = "THE ENGINEER",
		Rarity = "Rare",
		Desc = "Why fight when drones can?",
		Passive = "+10% duration",
		Mechanic = "DroneBay",
		MechanicText = "Drone Bay: +1 drone, drones deal +25% damage.",
		StartWeapon = "Drone",
		Stats = { Duration = 0.1 },
		Color = rgb(255, 150, 40),
		Accent = rgb(255, 215, 60),
		Unlock = { Fragments = 40 },
	},
	{
		Key = "Lucky",
		Name = "THE LUCKY",
		Rarity = "Rare",
		Desc = "Found a four-leaf clover. Twice.",
		Passive = "+50% luck",
		Mechanic = "Jackpot",
		MechanicText = "Jackpot: 67 events come sooner, chests offer 1 extra card.",
		StartWeapon = "Lightning",
		Stats = { Luck = 0.5 },
		Color = rgb(60, 190, 90),
		Accent = rgb(255, 205, 60),
		Unlock = { Fragments = 40 },
	},
	{
		Key = "Goober",
		Name = "THE GOOBER",
		Rarity = "Epic",
		Desc = "A friendly blob with even smaller friends.",
		Passive = "+10 max HP",
		Mechanic = "GooberFriends",
		MechanicText = "Goober Friends: 2 helpers from the start, +1 every 10 levels.",
		StartWeapon = "PulseBlast",
		Stats = { MaxHP = 10 },
		Color = rgb(120, 220, 90),
		Accent = rgb(255, 110, 190),
		Unlock = { Fragments = 70 },
	},
	{
		Key = "Void",
		Name = "THE VOID",
		Rarity = "Epic",
		Desc = "Quiet. Dark. Hungry.",
		Passive = "+5% damage",
		Mechanic = "VoidHunger",
		MechanicText = "Void Hunger: every quick kill adds +1% damage (up to +40%).",
		StartWeapon = "OrbitalBlades",
		Stats = { Might = 0.05 },
		Color = rgb(28, 24, 40),
		Accent = rgb(170, 90, 255),
		Unlock = { Fragments = 70 },
	},
	{
		Key = "Glitch",
		Name = "THE GLITCH",
		Rarity = "Epic",
		Desc = "Exists in two places. Mostly.",
		Passive = "+10% movement speed",
		Mechanic = "GlitchStep",
		MechanicText = "Glitch Step: instead of taking a hit, teleports away (every 5s).",
		StartWeapon = "Laser",
		Stats = { MoveSpeed = 0.1 },
		Color = rgb(40, 220, 230),
		Accent = rgb(255, 60, 200),
		Unlock = { Fragments = 70 },
	},
	{
		Key = "Overdrive",
		Name = "THE OVERDRIVE",
		Rarity = "Legendary",
		Desc = "Runs hot. Runs hotter when hurt.",
		Passive = "+5% attack speed",
		Mechanic = "Redline",
		MechanicText = "Redline: up to +60% attack speed as HP drops.",
		StartWeapon = "Rocket",
		Stats = { AttackSpeed = 0.05 },
		Color = rgb(255, 110, 30),
		Accent = rgb(255, 235, 80),
		Unlock = { Fragments = 110 },
	},
	{
		Key = "SixSeven",
		Name = "THE 67",
		Rarity = "Mythic",
		Desc = "Nobody knows why. It just is.",
		Passive = "+6.7% damage and XP, +67% luck",
		Mechanic = "SixtySeven",
		MechanicText = "Every 67th kill fires a free 67 BLAST. 67 events 3x more likely.",
		StartWeapon = "Orb67",
		Stats = { Might = 0.067, Growth = 0.067, Luck = 0.67 },
		Color = rgb(120, 60, 200),
		Accent = rgb(255, 205, 50),
		Unlock = { Fragments = 167, Achievement = "Witness67" },
	},
	{
		Key = "Unknown",
		Name = "THE UNKNOWN",
		Rarity = "Secret",
		Desc = "Came from somewhere else.",
		Passive = "+15% damage, attack speed, XP and max HP",
		Mechanic = "Unknown",
		MechanicText = "Starts with 2 random abilities and 1 revive.",
		StartWeapon = "ChainLightning",
		Stats = { Might = 0.15, AttackSpeed = 0.15, Growth = 0.15, MaxHPMult = 0.15, Revives = 1 },
		Color = rgb(18, 18, 24),
		Accent = rgb(240, 240, 255),
		Unlock = { Achievement = "DefeatThe67" },
		Secret = true,
	},
} :: any)

local HeroData = {}
HeroData.List = LIST
HeroData.ByKey = {} :: { [string]: HeroDef }
for _, def in LIST do
	HeroData.ByKey[def.Key] = def
end
HeroData.Default = "Rookie"

return HeroData
