return {
	{
		name = "Heavy Lifting",
		chapter = "Crates and Lifts",
		hint = "The number on the crate is how many pals must push it.",
		map = {
			"                                                      ",
			"                                                      ",
			"                                                      ",
			"                                                      ",
			"                                                      ",
			"                                                      ",
			"          ############                                ",
			"          ############                                ",
			"              33                                      ",
			"  S           33                  K             D     ",
			"#########################  #############  ############",
			"#########################^^#############  ############",
			"########################################  ############",
		},
	},
	{
		name = "Lift Off",
		chapter = "Crates and Lifts",
		hint = "Everyone on the lift, then over the spikes.",
		lift = { need = 99, rise = 4 },
		map = {
			"                                                  ",
			"                                                  ",
			"                                                  ",
			"                                                  ",
			"                                                  ",
			"                ######                            ",
			"                ######                            ",
			"                ######                            ",
			"                ######                            ",
			"  S        LLLLL######      K      ^^       D     ",
			"##################################################",
			"##################################################",
			"##################################################",
		},
	},
	{
		name = "Step by Step",
		chapter = "Crates and Lifts",
		hint = "A crate to climb, stairs, then a crate to push.",
		map = {
			"                                                                     ",
			"                                                                     ",
			"                                                                     ",
			"                                                                     ",
			"                                                                     ",
			"                                                                     ",
			"                                 ##########                          ",
			"                   ###    ###    ##########                          ",
			"                   ###   #####       33                              ",
			"  S          1     ###  #######      33                K       D     ",
			"##############################################  #####################",
			"##############################################^^#####################",
			"#####################################################################",
		},
	},
	{
		name = "Crate and Lift",
		chapter = "Crates and Lifts",
		hint = "Crate, lift, a high key and a team plate.",
		lift = { need = 99, rise = 4 },
		button = { need = 4, latch = true },
		map = {
			"                                                              x             ",
			"                                                              x             ",
			"                                                              x             ",
			"                                                              x             ",
			"                                                              x             ",
			"                                    ######      K             x             ",
			"          ############              ######     ###            x             ",
			"          ############              ######                    x             ",
			"              33                    ######                    x             ",
			"  S           33               LLLLL######              b     x       D     ",
			"#########################  #################################################",
			"#########################^^#################################################",
			"############################################################################",
		},
	},
	{
		name = "Wobble Bridge",
		chapter = "Seesaws and Sand",
		hint = "The plank tilts - stand on both ends to keep it level.",
		map = {
			"                                               ",
			"                                               ",
			"                                               ",
			"                                               ",
			"                                               ",
			"                                               ",
			"                                               ",
			"                                               ",
			"                                               ",
			"  S                        K             D     ",
			"############=========##########################",
			"############         ##########################",
			"############         ##########################",
		},
	},
	{
		name = "Sandy Steps",
		chapter = "Seesaws and Sand",
		hint = "Sand, stairs and more sand. Don't stop!",
		map = {
			"                                                            ",
			"                                                            ",
			"                                                            ",
			"                                                            ",
			"                                                            ",
			"                                                            ",
			"                                 K                          ",
			"                                ooo                         ",
			"                       ###                                  ",
			"  S                   #####                           D     ",
			"#############oooo#########################ooooo#############",
			"#############    #########################     #############",
			"#############    #########################     #############",
		},
	},
	{
		name = "Hourglass",
		chapter = "Seesaws and Sand",
		hint = "Sand and a clock: 90 seconds.",
		time = 90,
		map = {
			"                                                              ",
			"                                                              ",
			"                                                              ",
			"                                                              ",
			"                                                              ",
			"                                                              ",
			"                                                              ",
			"                                                              ",
			"                                                              ",
			"  S                                   K                 D     ",
			"#############ooooo#####=========#############oooo#############",
			"#############     #####         #############    #############",
			"#############     #####         #############    #############",
		},
	},
	{
		name = "Sand Seesaw",
		chapter = "Seesaws and Sand",
		hint = "Two seesaws, sand and a high key - 100 seconds.",
		time = 100,
		map = {
			"                                                                   ",
			"                                                                   ",
			"                                                                   ",
			"                                                                   ",
			"                                                                   ",
			"                                                                   ",
			"                                      K                            ",
			"                                     ooo                           ",
			"                                                                   ",
			"  S                                                          D     ",
			"############=========#####ooooo###############=========############",
			"############         #####     ###############         ############",
			"############         #####     ###############         ############",
		},
	},
	{
		name = "Moving Floors",
		chapter = "Platforms and Two Colours",
		hint = "Hop on the moving platforms when they are low.",
		mover = { rise = 3, period = 4 },
		map = {
			"                                                ",
			"                                                ",
			"                                                ",
			"                                                ",
			"                                                ",
			"                                                ",
			"                                                ",
			"                                                ",
			"                                                ",
			"  S                     K                 D     ",
			"############  MM  ############  MM  ############",
			"############      ############      ############",
			"############      ############      ############",
		},
	},
	{
		name = "Pink Bridge",
		chapter = "Platforms and Two Colours",
		hint = "The pink bridge stays while someone holds the pink plate.",
		button2 = { need = 1, latch = false },
		mover = { rise = 3, period = 4 },
		map = {
			"                                                  ",
			"                                                  ",
			"                                                  ",
			"                                                  ",
			"                                                  ",
			"                                                  ",
			"                                                  ",
			"                                                  ",
			"                                                  ",
			"  S        c        c     K                 D     ",
			"#############hhhhhh#############  MM  ############",
			"#############      #############      ############",
			"#############      #############      ############",
		},
	},
	{
		name = "Ride and Hold",
		chapter = "Platforms and Two Colours",
		hint = "Hold the bridge, then catch the key over a platform.",
		mover = { rise = 3, period = 3.8 },
		button2 = { need = 1, latch = false },
		map = {
			"                                                                  ",
			"                                                                  ",
			"                                                                  ",
			"                                                                  ",
			"                                                                  ",
			"                                        K                         ",
			"                                                                  ",
			"                                                                  ",
			"                                                                  ",
			"  S                      c        c             j^^^        D     ",
			"############  MM  MM  #####hhhhhh#####  MM  ######################",
			"############          #####      #####      ######################",
			"############          #####      #####      ######################",
		},
	},
	{
		name = "Two Colours",
		chapter = "Platforms and Two Colours",
		hint = "Purple and pink plates in one level.",
		button = { need = 4, latch = true },
		button2 = { need = 1, latch = false },
		mover = { rise = 3, period = 3.8 },
		map = {
			"                  x                                             ",
			"                  x                                             ",
			"                  x                                             ",
			"                  x                                             ",
			"                  x                                             ",
			"                  x                                             ",
			"                  x                   K                         ",
			"                  x                  ###                        ",
			"                  x                                             ",
			"  S         b     x    c        c                         D     ",
			"#########################hhhhhh###############  MM  ############",
			"#########################      ###############      ############",
			"#########################      ###############      ############",
		},
	},
	{
		name = "Cannonballs",
		chapter = "Cannons and the Chase",
		hint = "Jump over the cannonballs and hide behind blocks.",
		cannon = { interval = 2.8, speed = 12 },
		map = {
			"                                            ",
			"                                            ",
			"                                            ",
			"                                            ",
			"                                            ",
			"                                            ",
			"                                            ",
			"                                            ",
			"                                            ",
			"  S           K      #    #      <    D     ",
			"############################################",
			"############################################",
			"############################################",
		},
	},
	{
		name = "High and Low",
		chapter = "Cannons and the Chase",
		hint = "Cannonballs fly low and high. Time your jumps!",
		cannon = { interval = 2.6, speed = 13 },
		map = {
			"                                                        ",
			"                                                        ",
			"                                                        ",
			"                                                        ",
			"                                                        ",
			"                                                        ",
			"                                                        ",
			"          >                                             ",
			"                                                        ",
			"  S                       K      #    #      <    D     ",
			"########################################################",
			"########################################################",
			"########################################################",
		},
	},
	{
		name = "The Chase",
		chapter = "Cannons and the Chase",
		hint = "The screen scrolls by itself - keep up with the red wall!",
		scroll = { speed = 3.2, delay = 4 },
		map = {
			"                                                                  ",
			"                                                                  ",
			"                                                                  ",
			"                                                                  ",
			"                                                                  ",
			"                                                                  ",
			"                                                                  ",
			"                                                                  ",
			"                                                                  ",
			"  S                ^^      ##       K     j^^^              D     ",
			"############  ######################################  ############",
			"############  ######################################  ############",
			"############  ######################################  ############",
		},
	},
	{
		name = "Cannon Seesaw",
		chapter = "Cannons and the Chase",
		hint = "Balance the seesaw while cannonballs fly.",
		cannon = { interval = 2.6, speed = 13 },
		map = {
			"                                                                     ",
			"                                                                     ",
			"                                                                     ",
			"                                                                     ",
			"                                                                     ",
			"                                                                     ",
			"                                                                     ",
			"                                                                     ",
			"                                                                     ",
			"  S          #         <                 K      #         <    D     ",
			"##########################=========##################################",
			"##########################         ##################################",
			"##########################         ##################################",
		},
	},
}
